build:
	`nix-build ../shell.nix`/bin/elm make Main.elm --output elm.js

debug:
	`nix-build ../shell.nix`/bin/elm make Main.elm --debug --output elm.js

optimize:
	`nix-build ../shell.nix`/bin/elm make Main.elm --optimize --output elm.js
